# -*- coding: utf-8 -*-
"""Copy of Lab 3 Simulating MapReduce (Log Analysis – Count Requests per Status Code) .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DxO-tvrgKcQYyFYAGKfdg-hjzh4neeug

Creating a simple dataset.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile weblogs.txt
# # Date, Time, IP, Method, URL, Status, ResponseSize
# 2025-10-10,12:01:32,192.168.1.2,GET,/index.html,200,1024
# 2025-10-10,12:01:33,192.168.1.3,GET,/products.html,200,850
# 2025-10-10,12:01:35,192.168.1.4,GET,/contact.html,404,512
# 2025-10-10,12:01:38,192.168.1.5,POST,/checkout,500,128
# 2025-10-10,12:01:41,192.168.1.6,GET,/index.html,200,1024
# 2025-10-10,12:01:45,192.168.1.7,GET,/images/logo.png,200,256
# 2025-10-10,12:01:48,192.168.1.8,GET,/about.html,404,512
# 2025-10-10,12:01:53,192.168.1.9,POST,/login,403,64
# 2025-10-10,12:02:01,192.168.1.10,GET,/index.html,200,1024
# 2025-10-10,12:02:07,192.168.1.11,POST,/checkout,500,128
# 2025-10-10,12:02:12,192.168.1.12,GET,/contact.html,404,512
# 2025-10-10,12:02:15,192.168.1.13,GET,/index.html,200,1024
# 2025-10-10,12:02:21,192.168.1.14,GET,/products.html,200,850
# 2025-10-10,12:02:23,192.168.1.15,GET,/about.html,404,512
# 2025-10-10,12:02:29,192.168.1.16,POST,/checkout,500,128
# 2025-10-10,12:02:31,192.168.1.17,GET,/images/logo.png,200,256
# 2025-10-10,12:02:34,192.168.1.18,GET,/contact.html,404,512
# 2025-10-10,12:02:38,192.168.1.19,POST,/login,403,64
# 2025-10-10,12:02:41,192.168.1.20,GET,/index.html,200,1024
# 2025-10-10,12:02:47,192.168.1.21,GET,/products.html,200,850
#

"""Implement the Mapper"""

def mapper(line):
    fields = line.strip().split(",")
    if len(fields) != 7 or fields[0].startswith('#'):
        return []

    #code status
    status = fields[5]

    return [(status, 1)]

"""Shuffle Phase"""

from collections import defaultdict

def shuffle(mapped_data):
    grouped = defaultdict(list)
    for key, value in mapped_data:
        grouped[key].append(value)
    return grouped

"""Reducer Phase"""

from collections import defaultdict

def reducer(mapped_data):
    grouped = defaultdict(int)
    for key, value in mapped_data:
        grouped[key] += value
    return grouped

"""Combine the Phases"""

# Mapper
mapped = []
with open("weblogs.txt", "r") as f:
    for line in f:
        mapped.extend(mapper(line))

# Reduce
reduced = reducer(mapped)

for code, count in sorted(reduced.items()):
    print(f"HTTP {code}: {count} requests")